apiVersion: v1
kind: Service
metadata:
  labels:
    run: grommet-test
  name: grommet-test
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: grommet-test
  sessionAffinity: None
  type: LoadBalancer
