apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2016-11-08T22:51:58Z
  generation: 2
  labels:
    run: grommet-test
  name: grommet-test
  namespace: default
  resourceVersion: "3590501"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/grommet-test
  uid: f421a70a-a605-11e6-b4b6-42010af00158
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grommet-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: grommet-test
    spec:
      containers:
      - image: us.gcr.io/fun-project-146321/grommet-test:v9
        imagePullPolicy: IfNotPresent
        name: grommet-test
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
