apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    run: grommet-test
  name: grommet-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grommet-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: grommet-test
    spec:
      containers:
      - image: us.gcr.io/fun-project-146321/grommet-test:v10
        imagePullPolicy: IfNotPresent
        name: grommet-test
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
